import type { NextPage } from 'next';
import Head from 'next/head';
import Tracks from '../components/Tracks';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="text-3xl font-bold text-gray-900">Tameablemist Web</h1>
        <div>
          <Tracks />
        </div>
      </main>
    </div>
  );
};

export default Home;
